In [17]:
import pickle
import sys
import os
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, precision_score, recall_score

In [2]:
sys.path.append('C:/Users/rsh15/Desktop/seunghuni/udacity/ud120-projects/tools')
from feature_format import featureFormat,targetFeatureSplit

In [3]:
os.chdir('C:/Users/rsh15/Desktop/seunghuni/udacity/ud120-projects/final_project')
data_dict = pickle.load(open('final_project_dataset.pkl','r'))

In [5]:
### add more features to features_list!
features_list = ["poi", "salary"]

data = featureFormat(data_dict, features_list)
labels, features = targetFeatureSplit(data)

# Number of POIs in Test Set

In [8]:
x_train, x_test, y_train, y_test = train_test_split(features,labels,test_size=0.3,random_state=42)

In [10]:
np.unique(y_test,return_counts=True)

(array([0., 1.]), array([25,  4], dtype=int64))

# Number of True Positives

In [15]:
dt = DecisionTreeClassifier()
dt_pre = dt.fit(x_train,y_train).predict(x_test,y_test)
dt_pre

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
confusion_matrix(y_test,dt_pre)

array([[21,  4],
       [ 4,  0]], dtype=int64)

# Unpacking Into Precision and Recall

In [22]:
precision_score(y_test,dt_pre)

0.0

# Recall of Your POI Identifier

In [23]:
recall_score(y_test,dt_pre)

0.0

# How Many True Positives?

In [25]:
predictions = [0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1]
true_labels = [0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0]

In [46]:
len([1 for a,b in zip(predictions,true_labels) if (a==1)&(b==1)])

6

# How Many True Negatives?


In [48]:
len([1 for a,b in zip(predictions,true_labels) if (a==0)&(b==0)])

2

# False Positives?

In [49]:
len([1 for a,b in zip(predictions,true_labels) if (a==1)&(b==0)])

3

# False Negatives?


In [50]:
len([1 for a,b in zip(predictions,true_labels) if (a==0)&(b==1)])

2

# Precision

In [64]:
tp = float(len([1 for a,b in zip(predictions,true_labels) if (a==1)&(b==1)]))
fp = float(len([1 for a,b in zip(predictions,true_labels) if (a==1)&(b==0)]))

In [68]:
round(tp/(tp+fp),3)

0.667

# Recall

In [66]:
fn = float(len([1 for a,b in zip(predictions,true_labels) if (a==0)&(b==1)]))

In [69]:
round(tp/(tp+fn),3)

0.75