Lab12 - RNN Basics

 * RNN,LSTM등의 특정 Cell을 선언하고, 이를 Loop하는 방식
 * 두가지를 결합한 API를 활용하는 방식
 
Tensorflow에서 RNN이 데이터를 전달받는 방식은
(Batch_size, Sequence Length, Input dimension)으로 받는다.

# Setup

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

tf.__version__

'2.3.1'

In [2]:
h = [1,0,0,0]
e = [0,1,0,0]
l = [0,0,1,0]
o = [0,0,0,1]

In [3]:
x_data = np.array([[h]],dtype=np.float32)

# Using Single Sequence

In [4]:
hidden_size=2

In [5]:
cell = layers.SimpleRNNCell(units=hidden_size)
rnn = layers.RNN(cell, return_sequences=True, return_state=True)
outputs, states = rnn(x_data)

In [6]:
# equivalent to above
# rnn = layers.SimpleRNN(units=hidden_size, return_sequences=True, return_state=True)
# outputs, states = rnn(x_data)

In [7]:
print('x_data: {}, shape: {}'.format(x_data, x_data.shape))
print('outputs: {}, shape: {}'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

# 같은 값이지만 다른 Shape를 갖는 것은
# output은 전체 Sequence에 해당하는 Hidden State값을 가지고 있고,
# State는 Sequence에 마지막 Hidden State값만 가지고 있기 때문이다.

x_data: [[[1. 0. 0. 0.]]], shape: (1, 1, 4)
outputs: [[[-0.14987229 -0.44768575]]], shape: (1, 1, 2)
states: [[-0.14987229 -0.44768575]], shape: (1, 2)


# Multiple Sequences

In [25]:
x_data = np.array([[h,e,l,l,o]], dtype=np.float32)
print(x_data)
x_data.shape

[[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]]


(1, 5, 4)

In [26]:
hidden_size = 2

In [27]:
rnn = layers.SimpleRNN(units=2, return_sequences=True, return_state=True)
outputs, states = rnn(x_data)

In [28]:
print('x_data: {}, shape: {} \n'.format(x_data, x_data.shape))
print('outputs: {}, shape: {} \n'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]], shape: (1, 5, 4) 

outputs: [[[-0.44577113 -0.45457456]
  [ 0.16972812  0.40452874]
  [ 0.73866075 -0.19238974]
  [ 0.5728731   0.51898247]
  [ 0.5662095   0.19033885]]], shape: (1, 5, 2) 

states: [[0.5662095  0.19033885]], shape: (1, 2)


# Batching

In [31]:
x_data = np.array([[h,e,l,l,o],
                   [e,o,l,l,l],
                   [l,l,e,e,l]],dtype=np.float32)

In [37]:
hidden_size = 2
rnn = layers.SimpleRNN(units=2 ,return_sequences=True, return_state=True)
outputs, states = rnn(x_data)

In [38]:
print('x_data: {}, shape: {} \n'.format(x_data, x_data.shape))
print('outputs: {}, shape: {} \n'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]], shape: (3, 5, 4) 

outputs: [[[-0.22702853 -0.11145466]
  [-0.4940548  -0.2724251 ]
  [-0.09476262  0.168072  ]
  [ 0.36822638 -0.17729284]
  [ 0.13862139  0.24966243]]

 [[-0.28792375 -0.32909676]
  [-0.4883009   0.26226225]
  [ 0.02064602 -0.3384754 ]
  [ 0.37569115  0.32771802]
  [ 0.7062245  -0.23414429]]

 [[ 0.4173716   0.00479313]
  [ 0.6931142   0.08580765]
  [ 0.3796346  -0.2757777 ]
  [ 0.01843184  0.00620464]
  [ 0.43319196  0.00251562]]], shape: (3, 5, 2) 

states: [[ 0.13862139  0.24966243]
 [ 0.7062245  -0.23414429]
 [ 0.43319196  0.00251562]], shape: (3, 2)
